name = "RNNTrialStructures"
uuid = "1c0943b8-e38f-498f-b6a0-1f910535fd85"
authors = ["Roger Heirkstad <roger.herikstad@gmail.com>"]
version = "0.18.0"

[deps]
CRC32c = "8bf52ea8-c179-5cab-976a-9e18b702a9bc"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CRC32c = "1.11.0"
GeometryBasics = "0.5.10"
LinearAlgebra = "1.11.0"
Random = "1.11.0"
StableRNGs = "1.0.3"
StatsBase = "0.24.0 - 0.34.5"
Test = "1.11.0"
